services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8003:80"
    networks:
      - tc3-network
    restart: always

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    ports:
      - "5050:5000"
    volumes:
      - ./mlruns:/app/mlruns
    networks:
      - tc3-network
  
  training_lambda:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.lambda

    command: ["app.lambda_handler"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000 
    depends_on:
      - mlflow
    networks:
      - tc3-network

networks:
  tc3-network: