FROM python:3.11-slim

RUN pip install mlflow[extras] && pip install gunicorn

COPY ./requirements/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./src /app/src

WORKDIR /app/src

RUN python get_startd_monitoring.py

EXPOSE 5000
EXPOSE 5001

CMD mlflow ui --host 0.0.0.0 --port 5000 & evidently ui --host 0.0.0.0 --port 5001
