FROM python:3.11-slim

RUN pip install mlflow[extras] && pip install gunicorn

COPY ./requirements/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./src /app/src

COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

WORKDIR /app/src

RUN python get_startd_monitoring.py

EXPOSE 5000
EXPOSE 5001

CMD ["/app/entrypoint.sh"]