services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-volume:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    networks:
      - tc3-network

  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8003:80"
    depends_on:
      - db
    networks:
      - tc3-network
    restart: always

  web:
    build: .
    ports:
      - 8501:8501
    volumes:
      - .:/app
    command: streamlit run frontend/interface.py
    depends_on:
      - api
    networks:
      - tc3-network

volumes:
  db-volume:

networks:
  tc3-network: