services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8003:80"
    networks:
      - tc3-network
    restart: always

  mlflow:
    build: ./mlflow 
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns  
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  
    networks:
      - tc3-network
  
  training_lambda:
    build: ./training_lambda  
    command: ["app.lambda_handler"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000 
    depends_on:
      - mlflow
    networks:
      - tc3-network

networks:
  tc3-network: