name: Pipeline Deploy
on: 
    push:
        branches: [main]
jobs:
    requirements:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - name: Install Dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r ./requirements/requirements.txt
    
    training-model:
      runs-on: ubuntu-latest
      needs: requirements
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4      
        
        - name: Train Model && Generate PKL
          run: |
            python ./src/train.py

    deploy-aws:
      needs: training-model
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build image and push it to Amazon ECR
          id: build-deploy-image
          uses: whoan/docker-build-with-cache-action@v5
          with:
            username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            registry: ${{ steps.login-ecr.outputs.registry }}
            image_name: ${{ vars.AWS_ECR_REPOSITORY_NAME }}
            image_tag: ${{ github.sha }}
            dockerfile: Dockerfile
